/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheChat: typeof import('./src/components/TheChat.vue')['default']
    TheProp: typeof import('./src/components/TheProp.vue')['default']
    TheSideBar: typeof import('./src/components/TheSideBar.vue')['default']
  }
}
